<a href="https://colab.research.google.com/github/Rajesh165/test/blob/master/Farmer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [2]:
df = pd.read_csv('/content/filename.csv')
df.head()

,Unnamed: 0,temp(cel),mean_windspeed(km/hr),re_hum(%),cloud(okta),rain(mm),avg._no._rainyday,district,month_index
0,0,12.571663,4.861222,77.267091,1.525148,14.375759,0.9,Bhagalpur,1
1,1,16.876908,4.658724,76.001416,1.749436,13.976031,0.9,Bhagalpur,1
2,2,15.775776,3.505728,79.321824,1.713624,12.331613,0.9,Bhagalpur,1
3,3,12.903226,3.196545,79.323649,1.591761,12.337610,0.9,Bhagalpur,1
4,4,16.829754,4.926399,78.572965,1.469696,12.780349,0.9,Bhagalpur,1


In [3]:
df['district'].unique()

array(['Bhagalpur', 'chapra', 'Darbhanga', 'Dehri', 'Forbesganj', 'Gaya',
       'jamui', 'Motihari', 'Muzaffarpur', 'patna', 'Purnea', 'Raxaul',
       'Sabour', 'Supaul'], dtype=object)

In [4]:
df = df.sample(frac=1).reset_index(drop=True)
df.head()

,Unnamed: 0,temp(cel),mean_windspeed(km/hr),re_hum(%),cloud(okta),rain(mm),avg._no._rainyday,district,month_index
0,192,26.628775,5.776549,84.733925,4.717045,267.609441,12.6,jamui,8
1,382,27.835205,2.454083,77.052955,1.316347,1.786216,0.1,Sabour,11
2,71,18.129299,2.327370,61.217295,0.474804,5.802939,0.7,Darbhanga,3
3,47,33.636740,6.328996,58.974142,1.321902,29.849739,1.9,chapra,5
4,286,12.176079,2.771243,75.493902,1.595976,2.184539,0.4,patna,12


In [5]:
X=df[['temp(cel)','mean_windspeed(km/hr)','re_hum(%)','cloud(okta)','rain(mm)','avg._no._rainyday','month_index']]
y =df['district']

In [6]:
X

,temp(cel),mean_windspeed(km/hr),re_hum(%),cloud(okta),rain(mm),avg._no._rainyday,month_index
0,26.628775,5.776549,84.733925,4.717045,267.609441,12.6,8
1,27.835205,2.454083,77.052955,1.316347,1.786216,0.1,11
2,18.129299,2.327370,61.217295,0.474804,5.802939,0.7,3
3,33.636740,6.328996,58.974142,1.321902,29.849739,1.9,5
4,12.176079,2.771243,75.493902,1.595976,2.184539,0.4,12
...,...,...,...,...,...,...,...
5105,33.634359,6.308958,72.021468,4.078859,122.649733,6.0,6
5106,29.566933,8.912713,83.311395,6.280639,290.069570,11.5,8
5107,28.106910,1.602606,69.498552,0.482735,5.199477,0.3,11
5108,29.240592,3.909827,82.545773,5.424867,249.114583,9.8,9


In [7]:
y

0            jamui
1           Sabour
2        Darbhanga
3           chapra
4            patna
           ...    
5105        chapra
5106        Raxaul
5107     Darbhanga
5108     Bhagalpur
5109    Forbesganj
Name: district, Length: 5110, dtype: object

In [8]:

lb = preprocessing.LabelEncoder()
y=lb.fit_transform(y)
y

array([12,  9,  1, ...,  1,  0,  3])

In [9]:
X = X.iloc[:,:].values
X

array([[2.66287747e+01, 5.77654916e+00, 8.47339245e+01, ...,
        2.67609441e+02, 1.26000000e+01, 8.00000000e+00],
       [2.78352047e+01, 2.45408263e+00, 7.70529553e+01, ...,
        1.78621568e+00, 1.00000000e-01, 1.10000000e+01],
       [1.81292986e+01, 2.32736957e+00, 6.12172950e+01, ...,
        5.80293877e+00, 7.00000000e-01, 3.00000000e+00],
       ...,
       [2.81069103e+01, 1.60260571e+00, 6.94985517e+01, ...,
        5.19947654e+00, 3.00000000e-01, 1.10000000e+01],
       [2.92405919e+01, 3.90982692e+00, 8.25457730e+01, ...,
        2.49114583e+02, 9.80000000e+00, 9.00000000e+00],
       [1.79317359e+01, 3.10804634e+00, 7.86611118e+01, ...,
        6.54023000e+00, 3.00000000e-01, 1.10000000e+01]])

In [10]:
  
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.25, random_state=0)

In [11]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier.fit(x_train, y_train)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [14]:
import joblib
filename = 'district.csv'
joblib.dump(classifier,filename)

['district.csv']

In [16]:
model = joblib.load('district.csv')
y_pred = model.predict(x_test)
y_pred

array([10, 10,  4, ...,  2,  5,  7])

In [17]:
score = model.score(x_test,y_test)
score

0.9694835680751174

In [18]:
output = lb.inverse_transform(y_pred)
output

array(['Supaul', 'Supaul', 'Gaya', ..., 'Dehri', 'Motihari', 'Purnea'],
      dtype=object)